name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: npm install
    - name: Build
      run: make
    - name: Test
      run: npx elm-test
    - uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read
      env:
          AWS_S3_BUCKET: 'i.ohlasy.info'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
          DEST_DIR: 'upload'